// SPDX-License-Identifier: Apache-2.0
// GENERATED by tools/gen_registry.py from registry/*.toml (ADR 0012).
// Do not hand-edit; run the `regenerate-registry` target instead.
#pragma once

#include "misbklv/types.hpp"

namespace misbklv::gen {

inline constexpr SpecialValue uas_0601_specials_13[] = {{2147483648ull}};
inline constexpr SpecialValue uas_0601_specials_14[] = {{2147483648ull}};

inline constexpr ItemDescriptor uas_0601_items[] = {
    { .tag = 1, .name = "Checksum", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone },
    { .tag = 2, .name = "Precision Time Stamp", .units = "microseconds", .kind = ValueKind::UInt, .variable = false, .fixed_len = 8, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory },
    { .tag = 5, .name = "Platform Heading Angle", .units = "deg", .kind = ValueKind::LinearLDS, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 360.0}, .specials = {}, .flags = kNone },
    { .tag = 6, .name = "Platform Pitch Angle", .units = "deg", .kind = ValueKind::LinearLDS, .variable = false, .fixed_len = 2, .is_signed = true, .map = {-20.0, 20.0}, .specials = {}, .flags = kNone },
    { .tag = 7, .name = "Platform Roll Angle", .units = "deg", .kind = ValueKind::LinearLDS, .variable = false, .fixed_len = 2, .is_signed = true, .map = {-50.0, 50.0}, .specials = {}, .flags = kNone },
    { .tag = 11, .name = "Image Source Sensor", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone },
    { .tag = 12, .name = "Image Coordinate System", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone },
    { .tag = 13, .name = "Sensor Latitude", .units = "deg", .kind = ValueKind::LinearLDS, .variable = false, .fixed_len = 4, .is_signed = true, .map = {-90.0, 90.0}, .specials = uas_0601_specials_13, .flags = kNone },
    { .tag = 14, .name = "Sensor Longitude", .units = "deg", .kind = ValueKind::LinearLDS, .variable = false, .fixed_len = 4, .is_signed = true, .map = {-180.0, 180.0}, .specials = uas_0601_specials_14, .flags = kNone },
    { .tag = 15, .name = "Sensor True Altitude", .units = "m", .kind = ValueKind::LinearLDS, .variable = false, .fixed_len = 2, .is_signed = false, .map = {-900.0, 19000.0}, .specials = {}, .flags = kNone },
    { .tag = 65, .name = "UAS Datalink LS Version Number", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory },
};

inline constexpr Registry uas_0601{ "UAS_0601", uas_0601_items };

}  // namespace misbklv::gen
