// SPDX-License-Identifier: Apache-2.0
// GENERATED by tools/gen_registry.py from registry/*.toml (ADR 0012).
// Do not hand-edit; run the `regenerate-registry` target instead.
#pragma once

#include "misbklv/types.hpp"

namespace misbklv::gen {


inline constexpr ItemDescriptor composite_imaging_1602_items[] = {
    { .tag = 1, .name = "Precision Time Stamp", .units = "microseconds", .kind = ValueKind::UInt, .variable = false, .fixed_len = 8, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 2, .name = "Document Version", .units = "", .kind = ValueKind::UInt, .variable = true, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 3, .name = "Source Image Rows", .units = "pixels", .kind = ValueKind::UInt, .variable = true, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 4, .name = "Source Image Columns", .units = "pixels", .kind = ValueKind::UInt, .variable = true, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 5, .name = "Source Image AOI Rows", .units = "pixels", .kind = ValueKind::UInt, .variable = true, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 6, .name = "Source Image AOI Columns", .units = "pixels", .kind = ValueKind::UInt, .variable = true, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 7, .name = "Source Image AOI Position X", .units = "pixels", .kind = ValueKind::Int, .variable = true, .fixed_len = 4, .is_signed = true, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 8, .name = "Source Image AOI Position Y", .units = "pixels", .kind = ValueKind::Int, .variable = true, .fixed_len = 4, .is_signed = true, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 9, .name = "Sub-Image Rows", .units = "pixels", .kind = ValueKind::UInt, .variable = true, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 10, .name = "Sub-Image Columns", .units = "pixels", .kind = ValueKind::UInt, .variable = true, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 11, .name = "Sub-Image Position X", .units = "pixels", .kind = ValueKind::Int, .variable = true, .fixed_len = 4, .is_signed = true, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 12, .name = "Sub-Image Position Y", .units = "pixels", .kind = ValueKind::Int, .variable = true, .fixed_len = 4, .is_signed = true, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 13, .name = "Active Sub-Image Rows", .units = "pixels", .kind = ValueKind::UInt, .variable = true, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 14, .name = "Active Sub-Image Columns", .units = "pixels", .kind = ValueKind::UInt, .variable = true, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 15, .name = "Active Sub-Image Offset X", .units = "pixels", .kind = ValueKind::Int, .variable = true, .fixed_len = 4, .is_signed = true, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 16, .name = "Active Sub-Image Offset Y", .units = "pixels", .kind = ValueKind::Int, .variable = true, .fixed_len = 4, .is_signed = true, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 17, .name = "Transparency", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 18, .name = "Z-Order", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
};

inline constexpr Registry composite_imaging_1602{ "COMPOSITE_IMAGING_1602", composite_imaging_1602_items, {} };

}  // namespace misbklv::gen

namespace misbklv::tags {

// Named ST tags for the COMPOSITE_IMAGING_1602 registry (ADR 0018 follow-on).
enum class CompositeImaging1602 : std::uint16_t {
    PrecisionTimeStamp = 1,
    DocumentVersion = 2,
    SourceImageRows = 3,
    SourceImageColumns = 4,
    SourceImageAOIRows = 5,
    SourceImageAOIColumns = 6,
    SourceImageAOIPositionX = 7,
    SourceImageAOIPositionY = 8,
    SubImageRows = 9,
    SubImageColumns = 10,
    SubImagePositionX = 11,
    SubImagePositionY = 12,
    ActiveSubImageRows = 13,
    ActiveSubImageColumns = 14,
    ActiveSubImageOffsetX = 15,
    ActiveSubImageOffsetY = 16,
    Transparency = 17,
    ZOrder = 18,
};

}  // namespace misbklv::tags
