// SPDX-License-Identifier: Apache-2.0
// GENERATED by tools/gen_registry.py from registry/*.toml (ADR 0012).
// Do not hand-edit; run the `regenerate-registry` target instead.
#pragma once

#include "misbklv/types.hpp"

namespace misbklv::gen {


inline constexpr ItemDescriptor geo_registration_1601_items[] = {
    { .tag = 1, .name = "Document Version", .units = "", .kind = ValueKind::UInt, .variable = true, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 2, .name = "Algorithm Name", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 3, .name = "Algorithm Version", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 4, .name = "Correspondence Points - Row/Column", .units = "", .kind = ValueKind::MdArray, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 5, .name = "Correspondence Points - Latitude/Longitude", .units = "", .kind = ValueKind::MdArray, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 6, .name = "Second Image Name", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 7, .name = "Algorithm Configuration Identifier", .units = "", .kind = ValueKind::Bytes, .variable = false, .fixed_len = 16, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 8, .name = "Correspondence Points - Elevation", .units = "", .kind = ValueKind::MdArray, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 9, .name = "Correspondence Points - Row/Column Standard Deviation and Correlation Coefficients", .units = "", .kind = ValueKind::MdArray, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 10, .name = "Correspondence Points - Latitude/Longitude/Elevation Standard Deviation and Correlation Coefficients", .units = "", .kind = ValueKind::MdArray, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
};

inline constexpr Registry geo_registration_1601{ "GEO_REGISTRATION_1601", geo_registration_1601_items, {} };

}  // namespace misbklv::gen

namespace misbklv::tags {

// Named ST tags for the GEO_REGISTRATION_1601 registry (ADR 0018 follow-on).
enum class GeoRegistration1601 : std::uint16_t {
    DocumentVersion = 1,
    AlgorithmName = 2,
    AlgorithmVersion = 3,
    CorrespondencePointsRowColumn = 4,
    CorrespondencePointsLatitudeLongitude = 5,
    SecondImageName = 6,
    AlgorithmConfigurationIdentifier = 7,
    CorrespondencePointsElevation = 8,
    CorrespondencePointsRowColumnStandardDeviationAndCorrelationCoefficients = 9,
    CorrespondencePointsLatitudeLongitudeElevationStandardDeviationAndCorrelationCoefficients = 10,
};

}  // namespace misbklv::tags
