// SPDX-License-Identifier: Apache-2.0
// GENERATED by tools/gen_registry.py from registry/*.toml (ADR 0012).
// Do not hand-edit; run the `regenerate-registry` target instead.
#pragma once

#include "misbklv/types.hpp"

namespace misbklv::gen {


inline constexpr ItemDescriptor sarmi_1206_items[] = {
    { .tag = 1, .name = "Grazing Angle", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 90.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 2, .name = "Ground Plane Squint Angle", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {-90.0, 90.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 3, .name = "Look Direction", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 4, .name = "Image Plane", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 5, .name = "Range Resolution", .units = "m", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 4, .is_signed = false, .map = {0.0, 1000000.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 6, .name = "Cross-Range Resolution", .units = "m", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 4, .is_signed = false, .map = {0.0, 1000000.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 7, .name = "Range Image Plane Pixel Size", .units = "m", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 4, .is_signed = false, .map = {0.0, 1000000.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 8, .name = "Cross-Range Image Plane Pixel Size", .units = "m", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 4, .is_signed = false, .map = {0.0, 1000000.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 9, .name = "Image Rows", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 10, .name = "Image Columns", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 11, .name = "Range Direction Angle Relative to True North", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 360.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 12, .name = "True North Direction Relative to Top Image Edge", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 360.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 13, .name = "Range Layover Angle Relative to True North", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 360.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 14, .name = "Ground Aperture Angular Extent", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 90.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 15, .name = "Aperture Duration", .units = "microseconds", .kind = ValueKind::UInt, .variable = false, .fixed_len = 4, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 16, .name = "Ground Track Angle", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 360.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 17, .name = "Minimum Detectable Velocity", .units = "m/s", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 100.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 18, .name = "True Pulse Repetition Frequency", .units = "Hz", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 4, .is_signed = false, .map = {0.0, 1000000.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 19, .name = "Pulse Repetition Frequency Scale Factor", .units = "", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 1.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 20, .name = "Transmit RF Center Frequency", .units = "Hz", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 4, .is_signed = false, .map = {0.0, 1000000000000.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 21, .name = "Transmit RF Bandwidth", .units = "Hz", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 4, .is_signed = false, .map = {0.0, 100000000000.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 22, .name = "Radar Cross Section Scale Factor Polynomial", .units = "", .kind = ValueKind::MdArray, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 23, .name = "Reference Frame Precision Time Stamp", .units = "microseconds", .kind = ValueKind::UInt, .variable = false, .fixed_len = 8, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 24, .name = "Reference Frame Grazing Angle", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 90.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 25, .name = "Reference Frame Ground Plane Squint Angle", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {-90.0, 90.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 26, .name = "Reference Frame Range Direction Angle Relative to True North", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 360.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 27, .name = "Reference Frame Range Layover Angle Relative to True North", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 360.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 28, .name = "Document Version", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
};

inline constexpr Registry sarmi_1206{ "SARMI_1206", sarmi_1206_items, {} };

}  // namespace misbklv::gen

namespace misbklv::tags {

// Named ST tags for the SARMI_1206 registry (ADR 0018 follow-on).
enum class Sarmi1206 : std::uint16_t {
    GrazingAngle = 1,
    GroundPlaneSquintAngle = 2,
    LookDirection = 3,
    ImagePlane = 4,
    RangeResolution = 5,
    CrossRangeResolution = 6,
    RangeImagePlanePixelSize = 7,
    CrossRangeImagePlanePixelSize = 8,
    ImageRows = 9,
    ImageColumns = 10,
    RangeDirectionAngleRelativeToTrueNorth = 11,
    TrueNorthDirectionRelativeToTopImageEdge = 12,
    RangeLayoverAngleRelativeToTrueNorth = 13,
    GroundApertureAngularExtent = 14,
    ApertureDuration = 15,
    GroundTrackAngle = 16,
    MinimumDetectableVelocity = 17,
    TruePulseRepetitionFrequency = 18,
    PulseRepetitionFrequencyScaleFactor = 19,
    TransmitRFCenterFrequency = 20,
    TransmitRFBandwidth = 21,
    RadarCrossSectionScaleFactorPolynomial = 22,
    ReferenceFramePrecisionTimeStamp = 23,
    ReferenceFrameGrazingAngle = 24,
    ReferenceFrameGroundPlaneSquintAngle = 25,
    ReferenceFrameRangeDirectionAngleRelativeToTrueNorth = 26,
    ReferenceFrameRangeLayoverAngleRelativeToTrueNorth = 27,
    DocumentVersion = 28,
};

}  // namespace misbklv::tags
