// SPDX-License-Identifier: Apache-2.0
// GENERATED by tools/gen_registry.py from registry/*.toml (ADR 0012).
// Do not hand-edit; run the `regenerate-registry` target instead.
#pragma once

#include "misbklv/types.hpp"

namespace misbklv::gen {


inline constexpr ItemDescriptor security_0102_items[] = {
    { .tag = 1, .name = "Security Classification", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 2, .name = "Classifying Country and Releasing Instructions Country Coding Method", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 3, .name = "Classifying Country", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 4, .name = "Security-SCI/SHI Information", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 5, .name = "Caveats", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 6, .name = "Releasing Instructions", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 7, .name = "Classified By", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 8, .name = "Derived From", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 9, .name = "Classification Reason", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 10, .name = "Declassification Date", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 11, .name = "Classification and Marking System", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 12, .name = "Object Country Coding Method", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 13, .name = "Object Country Codes", .units = "", .kind = ValueKind::Bytes, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 14, .name = "Classification Comments", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 22, .name = "Version", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 2, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kMandatory, .child = RegistryId::None },
    { .tag = 23, .name = "Classifying Country and Releasing Instructions Country Coding Method Version Date", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 24, .name = "Object Country Coding Method Version Date", .units = "", .kind = ValueKind::Utf8, .variable = true, .fixed_len = 0, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
};

inline constexpr Registry security_0102{ "SECURITY_0102", security_0102_items, {} };

}  // namespace misbklv::gen

namespace misbklv::tags {

// Named ST tags for the SECURITY_0102 registry (ADR 0018 follow-on).
enum class Security0102 : std::uint16_t {
    SecurityClassification = 1,
    ClassifyingCountryAndReleasingInstructionsCountryCodingMethod = 2,
    ClassifyingCountry = 3,
    SecuritySCISHIInformation = 4,
    Caveats = 5,
    ReleasingInstructions = 6,
    ClassifiedBy = 7,
    DerivedFrom = 8,
    ClassificationReason = 9,
    DeclassificationDate = 10,
    ClassificationAndMarkingSystem = 11,
    ObjectCountryCodingMethod = 12,
    ObjectCountryCodes = 13,
    ClassificationComments = 14,
    Version = 22,
    ClassifyingCountryAndReleasingInstructionsCountryCodingMethodVersionDate = 23,
    ObjectCountryCodingMethodVersionDate = 24,
};

}  // namespace misbklv::tags
