// SPDX-License-Identifier: Apache-2.0
// GENERATED by tools/gen_registry.py from registry/*.toml (ADR 0012).
// Do not hand-edit; run the `regenerate-registry` target instead.
#pragma once

#include "misbklv/types.hpp"

namespace misbklv::gen {


inline constexpr ItemDescriptor vtarget_0903_items[] = {
    { .tag = 1, .name = "targetCentroid", .units = "", .kind = ValueKind::UInt, .variable = true, .fixed_len = 6, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 4, .name = "targetPriority", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 1, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 8, .name = "targetColor", .units = "", .kind = ValueKind::UInt, .variable = false, .fixed_len = 3, .is_signed = false, .map = {0.0, 0.0}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 10, .name = "targetLocationOffsetLat", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 3, .is_signed = false, .map = {-19.2, 19.2}, .specials = {}, .flags = kNone, .child = RegistryId::None },
    { .tag = 11, .name = "targetLocationOffsetLon", .units = "deg", .kind = ValueKind::IMAPB, .variable = false, .fixed_len = 3, .is_signed = false, .map = {-19.2, 19.2}, .specials = {}, .flags = kNone, .child = RegistryId::None },
};

inline constexpr Registry vtarget_0903{ "VTARGET_0903", vtarget_0903_items, {} };

}  // namespace misbklv::gen

namespace misbklv::tags {

// Named ST tags for the VTARGET_0903 registry (ADR 0018 follow-on).
enum class Vtarget0903 : std::uint16_t {
    TargetCentroid = 1,
    TargetPriority = 4,
    TargetColor = 8,
    TargetLocationOffsetLat = 10,
    TargetLocationOffsetLon = 11,
};

}  // namespace misbklv::tags
