#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate constexpr registry tables (ADR 0010) from TOML source (ADR 0012).

Usage: gen_registry.py <in.toml> <out.generated.hpp>

Validates the source and emits a self-contained header. Generated output is
committed; regenerate via this script or the `regenerate-registry` CMake target.
Requires Python >= 3.11 (stdlib tomllib).
"""
import sys

try:
    import tomllib  # Python >= 3.11
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # backport
    except ModuleNotFoundError:
        tomllib = None  # fall back to the minimal reader below

KIND = {
    "uint": "UInt", "int": "Int", "linear_lds": "LinearLDS", "imapb": "IMAPB",
    "utf8": "Utf8", "bytes": "Bytes", "nested_ls": "NestedLS", "pack": "Pack",
}
FIXED_KINDS = {"uint", "int", "linear_lds", "imapb"}   # length is meaningful
MAPPED_KINDS = {"linear_lds", "imapb"}


def die(msg):
    sys.exit(f"gen_registry: {msg}")


def _strip_comment(line):
    out, in_str = [], False
    for ch in line:
        if ch == '"':
            in_str = not in_str
        if ch == "#" and not in_str:
            break
        out.append(ch)
    return "".join(out)


def _scalar(text):
    text = text.strip()
    if text.startswith('"'):
        return text.strip('"')
    if text.startswith("["):
        inner = text[1:text.rindex("]")]
        return [x.strip().strip('"') for x in inner.split(",") if x.strip()]
    if text in ("true", "false"):
        return text == "true"
    if any(c in text for c in ".eE"):
        return float(text)
    return int(text, 0)


def _fallback_load(f):
    """Minimal TOML reader for the registry schema (comments, scalars, arrays,
    [[item]] / [[item.special]] arrays-of-tables). Used only when tomllib/tomli
    are absent (ADR 0012 open question)."""
    root, ctx = {}, None
    for raw in f.read().decode("utf-8").splitlines():
        line = _strip_comment(raw).strip()
        if not line:
            continue
        if line == "[[item]]":
            item = {}
            root.setdefault("item", []).append(item)
            ctx = item
        elif line == "[[item.special]]":
            item = root["item"][-1]
            sp = {}
            item.setdefault("special", []).append(sp)
            ctx = sp
        elif "=" in line:
            key, val = line.split("=", 1)
            target = ctx if ctx is not None else root
            target[key.strip()] = _scalar(val)
        else:
            die(f"fallback reader: cannot parse line: {raw!r}")
    return root


def load_toml(path):
    with open(path, "rb") as f:
        if tomllib is not None:
            return tomllib.load(f)
        return _fallback_load(f)


def validate(reg):
    seen = set()
    for it in reg["item"]:
        tag = it["tag"]
        if tag in seen:
            die(f"duplicate tag {tag} in registry {reg['registry']}")
        seen.add(tag)
        kind = it["kind"]
        if kind not in KIND:
            die(f"tag {tag}: unknown kind '{kind}'")
        if kind in FIXED_KINDS and "length" not in it:
            die(f"tag {tag}: kind '{kind}' needs a length")
        if kind in MAPPED_KINDS and not ("min" in it and "max" in it):
            die(f"tag {tag}: kind '{kind}' needs min and max")
        for sp in it.get("special", []):
            pat = int(str(sp["pattern"]), 0)
            width = it.get("length", 0) * 8
            if width and pat >= (1 << width):
                die(f"tag {tag}: special {sp['pattern']} exceeds {it['length']} bytes")


def cbool(b):
    return "true" if b else "false"


def emit(reg, out_path):
    ident = reg["registry"].lower()
    items = sorted(reg["item"], key=lambda i: i["tag"])
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// GENERATED by tools/gen_registry.py from registry/*.toml (ADR 0012).",
        "// Do not hand-edit; run the `regenerate-registry` target instead.",
        "#pragma once",
        "",
        '#include "misbklv/types.hpp"',
        "",
        "namespace misbklv::gen {",
        "",
    ]
    # per-item specials arrays
    for it in items:
        sp = it.get("special", [])
        if sp:
            pats = ", ".join(f"{{{int(str(s['pattern']), 0)}ull}}" for s in sp)
            lines.append(
                f"inline constexpr SpecialValue {ident}_specials_{it['tag']}[] = {{{pats}}};")
    lines.append("")
    lines.append(f"inline constexpr ItemDescriptor {ident}_items[] = {{")
    for it in items:
        kind = it["kind"]
        variable = kind not in FIXED_KINDS
        fixed_len = 0 if variable else it["length"]
        is_signed = it.get("signed", False)
        mn = it.get("min", 0.0)
        mx = it.get("max", 0.0)
        units = it.get("units", "")
        specials = (f"{ident}_specials_{it['tag']}" if it.get("special") else "{}")
        flags = "kMandatory" if "mandatory" in it.get("flags", []) else "kNone"
        lines.append(
            f'    {{ .tag = {it["tag"]}, .name = "{it["name"]}", .units = "{units}", '
            f".kind = ValueKind::{KIND[kind]}, .variable = {cbool(variable)}, "
            f".fixed_len = {fixed_len}, .is_signed = {cbool(is_signed)}, "
            f".map = {{{mn!r}, {mx!r}}}, .specials = {specials}, .flags = {flags} }},")
    lines.append("};")
    lines.append("")
    lines.append(
        f'inline constexpr Registry {ident}{{ "{reg["registry"]}", {ident}_items }};')
    lines.append("")
    lines.append("}  // namespace misbklv::gen")
    lines.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))


def main():
    if len(sys.argv) != 3:
        die("usage: gen_registry.py <in.toml> <out.generated.hpp>")
    reg = load_toml(sys.argv[1])
    if "item" not in reg:
        die("no [[item]] tables in source")
    validate(reg)
    emit(reg, sys.argv[2])
    print(f"gen_registry: {len(reg['item'])} items -> {sys.argv[2]}")


if __name__ == "__main__":
    main()
